name: 📚 Update Course Syllabus
description: Request to update or create a course syllabus using the NKD Agility syllabus system
title: "[SYLLABUS] Update syllabus for [COURSE NAME]"
labels: ["syllabus", "content", "training"]
projects: ["nkdAgility/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our course content! This template will help you request syllabus updates using our standardized syllabus system.

        All courses use the **immersive format** with external **syllabus.yaml** files for better maintainability.

        📖 **Reference**: See [syllabus-system.md](../docs/syllabus-system.md) for detailed documentation on the syllabus system.

        **Note**: Course overview, learning objectives, and target audience should be maintained in the course's front matter. This issue will also update the course front matter with `course_sessions` and `course_length` fields if provided.

  - type: textarea
    id: processing_instructions
    attributes:
      label: "🤖 Processing Instructions"
      description: "Instructions for AI agents and human reviewers (will be included in the issue)"
      value: |
        ## Processing Instructions

        ### Issue Processing Workflow:
        - [ ] **Locate Course**: Use the course code to find the course directory in `site/content/capabilities/training-courses/`
        - [ ] **Update Front Matter**: Add/update `course_length` and `course_sessions` fields in the course's `index.md` front matter if provided
        - [ ] **Create/Update Syllabus**: Process the provided YAML content into the course's `syllabus.yaml` file
        - [ ] **Validate Structure**: Ensure YAML syntax is correct and session durations align with total course hours
        - [ ] **Review Assignments**: Verify assignments follow immersive format principles (outcome-focused, adaptable, real-world application)
        - [ ] **Quality Check**: Confirm content meets NKD Agility training standards and aligns with target delivery audiences

        ### Key Validation Points:
        - [ ] **YAML Syntax**: Must be valid and properly formatted
        - [ ] **Duration Alignment**: Session durations should total to course hours unless specified otherwise
        - [ ] **Assignment Quality**: Focus on outcomes rather than specific outputs
        - [ ] **Learning Objectives**: Clear connection between sessions and course goals
        - [ ] **Immersive Format**: Assignments emphasize real-world application and reflection
    validations:
      required: true

  - type: input
    id: course_code
    attributes:
      label: Course Code
      description: The unique Course Code of the course (found in the course's front matter, e.g., "APS", "PAL-E")
      placeholder: "enter the course code"
    validations:
      required: true
  - type: dropdown
    id: update_type
    attributes:
      label: Update Type
      description: How should the syllabus content be handled?
      options:
        - "Replace - Completely replace existing syllabus"
        - "Merge - Merge with existing content (preserve existing sessions)"
        - "Add - Add new sessions to existing syllabus"
        - "Create - Create new syllabus file"
      default: 0
    validations:
      required: true
  - type: input
    id: total_hours
    attributes:
      label: Total Course Hours
      description: Total duration of the course in hours (will be added to course front matter as course_length)
      placeholder: "16"
    validations:
      required: true

  - type: input
    id: number_sessions
    attributes:
      label: Number of Sessions
      description: Total number of sessions (typically course hours / 2, will be added to course front matter as course_sessions)
      placeholder: "8"
    validations:
      required: true

  - type: textarea
    id: syllabus_before
    attributes:
      label: Pre-Course Content (syllabusBefore)
      description: YAML content for preparation materials shown before main syllabus
      render: yaml
      placeholder: |
        - title: "Course Preparation"
          link: "./preparation/"
          duration: 15
          type: page
          weight: 1
        - title: "Pre-reading: Scrum Guide"
          link: "https://scrumguides.org/"
          duration: 30
          type: guide
          weight: 2
    validations:
      required: false
  - type: textarea
    id: sessions_yaml
    attributes:
      label: Sessions YAML Content
      description: YAML content for the main syllabus sessions. Include all sessions with id, title, duration, content, and optional learningResources/assignments
      render: yaml
      placeholder: |
        - id: 1
          title: "Session Title"
          duration: 120
          content: |
            Session description and learning objectives...
          assignment:
            title: "Assignment Title"
            content: |
              Assignment description focusing on outcomes...
            examples: |
              - Example approach 1
              - Example approach 2
          learningResources:
          - title: "Resource Title"
            link: "https://example.com"
            duration: 10
            type: guide
            weight: 1
    validations:
      required: true

  - type: textarea
    id: special_considerations
    attributes:
      label: Special Considerations
      description: Any special requirements, dependencies, or considerations for this syllabus
      placeholder: |
        - Prerequisites: Previous course completion required
        - Dependencies: Requires access to specific tools
        - Notes: Custom duration for specific audience
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that would help with implementing this syllabus update
      placeholder: "Related issues, external requirements, timeline constraints..."
    validations:
      required: false
