name: Remove PR Environemnt on Close

on:
  pull_request:
    types: [closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: Site
          path: ./_site

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.NKDAGILITY_BOT_APP_ID }}
          private-key: ${{ secrets.NKDAGILITY_BOT_CLIENTSECRET }}

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ steps.app-token.outputs.token }}
          action: 'upload'
          app_location: ./_site
          skip_app_build: true
          skip_api_build: true
          output_location: ''
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
