name: Copilot Setup Steps

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    name: Setup Development Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
      
      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        with:
          powershell-version: '7.4.1'
      
      - name: Verify Installations
        shell: pwsh
        run: |
          # Verify Hugo installation
          hugo version
          
          # Verify .NET installation
          dotnet --info
          
          # Verify PowerShell installation
          $PSVersionTable
          
          Write-Output "All prerequisites installed successfully!"