name: Copilot Setup Steps

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    name: Setup Development Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"
      - name: Verify Installations
        shell: pwsh
        run: |
          # Verify Hugo installation
          hugo version

          # Verify .NET installation
          dotnet --info

          Write-Output "All prerequisites installed successfully!"
